### ISSUE TITLE
Connects to Chromecast device but does not send audio

### ISSUE THREAD

**Issue by whateva** [muammar/mkchromecast#14] opened 2016-08-20 18:44 UTC
Yes, I did turn it on in puvacontrol.
Ubuntu 16.04 LTS

```
mkchromecast v0.3.4

ay_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')

The IP of SHIELD is: 192.168.1.112
Your local IP is: 192.168.1.236

The media type string used is: audio/mpeg

Cast media controller status

CastStatus(is_active_input=True, is_stand_by=False, volume_level=1.0, volume_muted=False, app_id=u'CC1AD845', display_name=u'Default Media Receiver', namespaces=[u'urn:x-cast:com.google.cast.media', u'urn:x-cast:com.google.cast.inject'], session_id=u'8A22722C-03B3-487C-B840-39E68477221A', transport_id=u'mediashell-1', status_text=u'Ready To Cast')

Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the application at any time

192.168.1.112 - - [20/Aug/2016 13:36:13] "GET /stream HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.112', 42274)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
192.168.1.112 - - [20/Aug/2016 13:36:13] "GET /stream HTTP/1.1" 200 -

```

**Comment by M1cha** [comment] 2016-08-22 06:59
same for me. the problem may be that chromecast shows the empty album cover and a progress bar all the time and never really finishes loading.

**Comment by muammar** [comment] 2016-08-22 11:04
@whateva @M1cha thanks for the report. So, are you both using google cast devices for tv and not the google cast audio?.

**Comment by M1cha** [comment] 2016-08-22 11:11
@muammar I'm using the 2nd gen Chromecast for TV but I'm using Arch Linux and not Ubuntu.

**Comment by whateva** [comment] 2016-08-22 12:21
I'm using the Nvidia Shield TV, and I'm still using Ubuntu 16.04.

**Comment by muammar** [comment] 2016-08-22 15:23
Thanks for the information. I do not have a TV at home, but I will try my best to understand the problem.

**Comment by lefo59** [comment] 2016-08-23 04:29
Hi. I'm having the same trouble as M1cha. I'm running Xubuntu 16.04. Followed the directions to install exactly as written in OMG! Ubuntu's site. It looks like it should be working, but it's not. Pulseaudio is showing mkchromecast as the device, and the sound bar shows that something's going on.

**Comment by muammar** [comment] 2016-08-23 09:53
@lefo59 thanks for reporting. I suppose you are also experiencing this problem with google cast for TVs.  I have [asked in the issues' tracker of pychromecast upstream](https://github.com/balloob/pychromecast/issues/109)  to see if anybody knows about this problem. 

In [ OMG! Ubuntu's site](http://www.omgubuntu.co.uk/2016/08/cast-ubuntu-desktop-audio-chromecast), the article says it was tested on a TV!.  I am curious to know what is different in the setups presenting the problem with respect to the ones that not.

**Comment by M1cha** [comment] 2016-08-23 09:57
my chromecast is directly connected to my TV via HDMI. I don't have any extra hw like av receivers, etc. Also my TV doesn't support any special codec's like dts. It's a old lcd tv without internet etc.

**Comment by muammar** [comment] 2016-08-23 10:16
@M1cha for that setup I had found these links:

http://chromecastforum.net/chromecast-help/how-i-solved-my-'no-sound'-issue/
https://www.techjunkie.com/sound-tv-chromecast/

It happens when casting audio from google chrome to chromecasts attached via HDMI ports.

**Comment by M1cha** [comment] 2016-08-23 10:53
@muammar well I doubt it's any of these (they're just like "reconnect and restart" anyway). because my sound work with everything else(and I use my chromecast a lot. videostream, tab cast, youtube, GooglePlayAudio,...).

**Comment by muammar** [comment] 2016-08-23 17:39
@whateva @M1cha @lefo59 would you mind to download this file: https://raw.githubusercontent.com/muammar/mkchromecast/master/test.py and run it `python test.py`?. Does it do something in your devices?. 

Thanks.

**Comment by M1cha** [comment] 2016-08-23 17:47
@muammar the test.py works perfectly for me.

**Comment by muammar** [comment] 2016-08-23 17:57
@M1cha thanks. Let's do something else:

1. Launch  `mkchromecast.py -s`.
2. When it prompts to make you select your chromecast, don't do anything. 
3. Play whatever music you like, and select the `mkchromecast` sink in `pavucontrol`. 
4. Use your phone with the chrome application, and use as URL `http://YOURLOCALCOMPUTERIP:5000`. 

Do you hear the music?.

**Comment by M1cha** [comment] 2016-08-23 18:26
@muammar 
uhm I just read the logs (of the normal run) for the first time(I should have done that earlier) and I think I know what the prob is. The streaming server gets started on the wrong interface.

I'm on wifi(wlp2s0) with my 192.168.x.x IP, but mkchromecast shows: Your local IP is: 172.17.0.1,
which after running ifconfig seems to be a interface called docker0.

**Comment by muammar** [comment] 2016-08-23 18:31
@M1cha that's the problem then. That's why I made you run the tests. I am using [this function](https://github.com/muammar/mkchromecast/blob/master/mkchromecast/cast.py#L55) to guess the IP. So it doesn't play well when you have another active interface (as the one used by docker).

**Comment by M1cha** [comment] 2016-08-23 18:36
@muammar I just confirmed this by hardcoding the real ip and it works :D 
You're already discovering the chromecast device, can't you detect from which interface this message comes from?

**Comment by muammar** [comment] 2016-08-23 19:16
@M1cha I came with a very simple solution: https://github.com/muammar/mkchromecast/commit/7754b7b673da6d59e7d25873d5538ee2a65c9d2f. If you are using the git repo, do a `git pull` and tell me if it works.  That should at least solve your problem.

**Comment by M1cha** [comment] 2016-08-24 04:09
yes, unless I start up virtualbox and get another network device:
vboxnet0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.1  netmask 255.255.255.0  broadcast 192.168.0.255

which ofc makes mkchromecast break again.

**Comment by muammar** [comment] 2016-08-24 07:42
@M1cha thanks for replying. `netifaces` sees all network devices "virtual" and "physical". What a problem :P, but it is very interesting anyways.  I have installed `docker.io`, and I have the following network interfaces:

```
muammar@zarathustra /tmp 
  % /sbin/ifconfig                                                                                                                                     !10101
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:e3:f5:f1:a8  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 15754  bytes 22107965 (21.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15754  bytes 22107965 (21.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.22  netmask 255.255.255.0  broadcast 192.168.1.255
        ether a4:5e:60:d2:d2:f3  txqueuelen 1000  (Ethernet)
        RX packets 17729  bytes 15191742 (14.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15911  bytes 2603663 (2.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Using this function returns my ip `192.168.1.22`, regardless the presence of `docker0`:

```
def getNetworkIp():
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
    s.connect(('<broadcast>', 0))
    return s.getsockname()[0]

print (getNetworkIp()

```

And this one also seems to work:

```
import socket
def get_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # doesn't even have to be reachable
        s.connect(('10.255.255.255', 0)) 
        IP = s.getsockname()[0]
    except:
        IP = '127.0.0.1'
    finally:
        s.close()
    return IP
print(get_ip())
```

You can give a try downloading this gist: https://gist.github.com/muammar/b9daa1ff21edcf3b729d1c00999f988e

Source:  http://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib

**Comment by M1cha** [comment] 2016-08-24 08:10
@muammar both these functions return the correct address for me too :)

**Comment by muammar** [comment] 2016-08-24 08:11
@M1cha nice! Commit https://github.com/muammar/mkchromecast/commit/707f5da49eec138393a8e0f37cc605acc379ebb6 introduces the change.

**Comment by M1cha** [comment] 2016-08-24 08:16
@muammar casting works just fine now, thx :)

**Comment by muammar** [comment] 2016-08-24 08:18
@M1cha you are welcome!. Now hopefully @whateva and @lefo59's problem is related.

**Comment by lefo59** [comment] 2016-08-24 12:22
Sorry, work has been crazy. I'll try tonight.

**Comment by M1cha** [comment] 2016-09-14 11:41
@muammar I dunno what caused it(maybe the ffmpeg -re commit?) but the delay is 3 instead of 7s now. good work :)

**Comment by muammar** [comment] 2016-09-14 11:59
@M1cha hi!, yes it was the `-re` flag not being proper for 'live' devices. Nice to know it is working great. :)

**Comment by muammar** [comment] 2017-01-29 17:57
I am proceeding to close this issue. Please, feel free to re-open it if you think it is necessary. Thanks.

**Closed by muammar** 2017-01-29 17:57 UTC
Labels: help wanted

**Comment by avantbored** [comment] 2017-09-09 23:44
Hello,

I am experiencing a similar problem.

Running Ubuntu MATE 16.04.

I created the "cast.py" file in the mkchromecast directory. Only "docker0", for me, is "tun0." I made the changes. "tun0" is my local IP, whereas "wlp2s0" is my router IP.

However, mkchromecast currently shows: 

`The IP of [CCDEVICE] is: 192.168.1.100
Your local IP is: 10.63.10.6`

Please advise. I'm a total novice! Many thanks.

**Comment by muammar** [comment] 2017-09-09 23:53
@avantbored which version of Mkchromecast are you running?.

**Comment by avantbored** [comment] 2017-09-09 23:57
Hi muammar,

I am using 0.3.7.1

**Comment by muammar** [comment] 2017-09-10 00:04
@avantbored try passing your `IP` using the `--host`. Check an example here: https://github.com/muammar/mkchromecast/blob/master/mkchromecast/__init__.py#L190. 

Tell me if it works.

**Comment by avantbored** [comment] 2017-09-10 00:06
@muammar 

OK, I will! Only: not sure where to put this. Should I create a new file, or should edit "cast.py" or "mkchromecast.py" ?

**Comment by muammar** [comment] 2017-09-10 00:08
You just have to execute your command as follows:

```
mkchromecast --host 192.162.1.10 
```
or

```
python mkchromecast.py --host 192.162.1.10 
```

Does it make sense now?

**Comment by avantbored** [comment] 2017-09-10 00:14
@muammar 

I tried `--host`with my GCast IP. PulseAudio bar is jumping up and down, but audio is not playing.

**Comment by muammar** [comment] 2017-09-10 00:19
@avantbored the `IP` should be the local IP of your computer. If I understood correctly, you have virtual network devices that are conflicting with the discovering of IPs. Therefore, you have to pass to `--host` the local IP.

**Comment by avantbored** [comment] 2017-09-10 00:36
@muammar 

Currently streaming, but still no audio. '--host' is flagged with my local IP.

**Comment by avantbored** [comment] 2017-09-10 01:16
@muammar 

If it gives you any more context, I'm having the same issue with pulseaudio-dlna

**Comment by hetzge** [comment] 2021-02-17 19:48
In my case the problem was the firewall under mx-linux. After i disabled it with `sudo ufw disable` it is working fine :)
