### ISSUE TITLE
reboot cast device action crashes mkchromecast

### ISSUE THREAD

**Issue by pasikarkkainen** [muammar/mkchromecast#56] opened 2017-04-09 19:19 UTC
Every time when I try to click "reboot cast device" from the mkchromecast gui v0.3.7 (actually latest git master as of today, running on mac osx) it seems mkchromecast itself crashes, the system tray icon disappears, and osx tells me mkchromecast crashed unexpectedly.

Steps to reproduce:
- Start mkchromecast.
- Search for devices.
- Click Chromecast Audio device to choose it.
- Click "reboot cast device".

--> mkchromecast crashes. It's always reproducible, happens every time.

pychromecast is version 0.7.7, QT is 5.8.0, mac osx 10.11.6 El Capitan.

**Comment by muammar** [comment] 2017-04-09 19:21
Thanks for reporting this. I will try to reproduce this error, and I hope to get it solve soon.

**Comment by muammar** [comment] 2017-04-15 03:06
@pasikarkkainen I have pushed https://github.com/muammar/mkchromecast/commit/eabd067afe429fb3f9f0e72a777969f79aa8f671, and I think the problem is solved now. Does it work for you?.

**Comment by muammar** [comment] 2017-04-29 14:55
I am closing this report because it may have been fixed in the commit mentioned above. However, feel free to reopen this report.

**Closed by muammar** 2017-04-29 14:55 UTC
Labels: macOS, systray
