### ISSUE TITLE
Sony soundbar with cast support

### ISSUE THREAD

**Issue by mtcliff79** [muammar/mkchromecast#43] opened 2017-01-29 09:44 UTC
mkchromecast is able to detect my two sony soundbars right out of the box, very encouraging start! two issues that I have:

- the subwoofer connected to the sound bar does not play any audio when using mkchromecast. It does work will every other input for example the same audio source connected through HDMI and other chromecast sources.

- no matter which device i select (device 1, device 2 or a group) mkchromecast always casts to all speakers. good news is that its in perfect multiroom sync. Ideally I could only cast to one of the devices.

Running Ubuntu 16.10

**Comment by muammar** [comment] 2017-01-29 17:39
> mkchromecast is able to detect my two sony soundbars right out of the box, very encouraging start! two issues that I have:

>the subwoofer connected to the sound bar does not play any audio when using mkchromecast. It does work will every other input for example the same audio source connected through HDMI and other chromecast sources.

Let's get back to this after we  see if we can connect to the desired google cast device. 

>no matter which device i select (device 1, device 2 or a group) mkchromecast always casts to all speakers. good news is that its in perfect multiroom sync. Ideally I could only cast to one of the devices.
> Running Ubuntu 16.10

I think I may have fixed this issue. Are you using the deb packages or the github repo? if you are using the latter, please checkout in `devel` and try to run mkchromecast from console. 

Thanks for your report!.

**Comment by mtcliff79** [comment] 2017-01-30 10:00
I was using the deb package 0.3.6. I used the git code, subwoofer is now working perfectly. I can also select each soundbar independently. However when I select the multiroom group it would seem to play on the chromecast tv rather than the two soundbar configured into a group. When I removed the cc tv multiroom playback worked.

Another interesting thing to note was that the system tray sometimes has a tick on more than one device even if i'm casting to one speaker. Have not fully tested this however.

FYI my plan is to create a script in Kodi so that I can chromecast kodi audio to speakers using yatse remote.

**Comment by muammar** [comment] 2017-01-30 15:03
> I was using the deb package 0.3.6. I used the git code, subwoofer is now working perfectly. I can also select each soundbar independently. However when I select the multiroom group it would seem to play on the chromecast tv rather than the two soundbar configured into a group. When I removed the cc tv multiroom playback worked.

Good to know that the subwoofer is playing well. Out of curiosity, are you using the `master` or `devel` branch?. If you are not using the latter, can you test it, please?. The error with not correctly selecting the google cast device was because I used indexes instead of names. It turns out that the order in which google cast devices are discovered may change. I fixed that in `devel`.

>Another interesting thing to note was that the system tray sometimes has a tick on more than one device even if i'm casting to one speaker. Have not fully tested this however.

I know, I need to solve that :). Thanks for reporting it. 

>FYI my plan is to create a script in Kodi so that I can chromecast kodi audio to speakers using yatse remote.

It sounds nice. It is good to know this app is being useful.

**Comment by muammar** [comment] 2017-01-30 16:54
I decided to merge `devel` into `master`. So you can just `git pull` to test.

**Comment by mtcliff79** [comment] 2017-01-31 09:42
ok, updated and on first test all is working well!

**Comment by muammar** [comment] 2017-01-31 15:05
> ok, updated and on first test all is working well!

Thank you. I am closing this report. Please do not hesitate to reopen if the issue is not fixed.

**Closed by muammar** 2017-01-31 15:05 UTC
Labels: bug, Linux
