### ISSUE TITLE
Can't get mkchromecast installed on Linux mint.

### ISSUE THREAD

**Issue by steenstra** [muammar/mkchromecast#53] opened 2017-03-12 14:53 UTC
[Posted on stackexchange as well.](http://unix.stackexchange.com/posts/350932/edit)

I'm trying to install [mkchromecast][1] on Linux Mint.

Following the instructions on the website, I first tried:

    $ sudo apt-get install mkchromecast

Which returned:

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package mkchromecast

When this didn't work, I downloaded the .deb and tried this:

    $ sudo dpkg -i mkchromecast_0.3.6-3_all.deb

and got the following response:

    Selecting previously unselected package mkchromecast.
    (Reading database ... 244586 files and directories currently installed.)
    Preparing to unpack mkchromecast_0.3.6-3_all.deb ...
    Unpacking mkchromecast (0.3.6-3) ...
    dpkg: dependency problems prevent configuration of mkchromecast:
     mkchromecast depends on python-flask; however:
      Package python-flask is not installed.
     mkchromecast depends on python-pychromecast; however:
      Package python-pychromecast is not installed.
     mkchromecast depends on python-psutil; however:
      Package python-psutil is not installed.
     mkchromecast depends on vorbis-tools (>= 1.4.0); however:
      Package vorbis-tools is not installed.
     mkchromecast depends on lame (>= 3.99.0); however:
      Package lame is not installed.
     mkchromecast depends on flac (>= 1.3.0); however:
      Package flac is not installed.
     mkchromecast depends on python-pyqt5; however:
      Package python-pyqt5 is not installed.
     mkchromecast depends on youtube-dl; however:
      Package youtube-dl is not installed.

    dpkg: error processing package mkchromecast (--install):
     dependency problems - leaving unconfigured
    Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
    Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
    Processing triggers for mime-support (3.59ubuntu1) ...
    Processing triggers for man-db (2.7.5-1) ...
    Errors were encountered while processing:
     mkchromecast

A few Google searches led me to try:

    sudo gdebi mkchromecast_0.3.6-3_all.deb

Which returned:

    Reading package lists... Done
    Building dependency tree        
    Reading state information... Done
    Reading state information... Done
    This package is uninstallable
    Dependency is not satisfiable: python-pychromecast

So I downloaded the python-pychromecast.deb and:

    sudo gdebi python-pychromecast_0.7.7-2_all.deb

But it seems the right version of python-protobuf is not installed:

    Reading package lists... Done
    Building dependency tree        
    Reading state information... Done
    Reading state information... Done
    This package is uninstallable
    Dependency is not satisfiable: python-protobuf (>= 3)

However, if I run:

    sudo apt-get install python-protobuf

It tells me it already is on the newest version:

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    python-protobuf is already the newest version (2.6.1-1.3).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Therefore I forced an install of the right version with:

    sudo -H pip install --upgrade protobuf==3.2.0

But this gives this response:

    Requirement already up-to-date: protobuf==3.2.0 in /usr/local/lib/python2.7/dist-packages/protobuf-3.2.0-py2.7.egg
    Requirement already up-to-date: six>=1.9 in /usr/lib/python2.7/dist-packages (from protobuf==3.2.0)
    Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf==3.2.0)
    Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools->protobuf==3.2.0)
    Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools->protobuf==3.2.0)
    Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools->protobuf==3.2.0)

Which leads me to believe version >= 3 should be installed...

Can anyone tell me what I'm doing wrong? Thanks!

  [1]: http://mkchromecast.com/

**Comment by steenstra** [comment] 2017-03-12 16:19
Installing from source was successful.

**Comment by muammar** [comment] 2017-03-12 16:33
I was checking Linux mint's repositories, and there is no trace of mkchromecast. 

>Installing from source was successful.

Nice.  Correct me if I am wrong, but Mint is an Ubuntu's derivative. I imagine that from april ubuntu is having this app in their repos and therefore Mint will do as well (eventually). Please, feel free to close this report if you think that the issue is fixed. Thanks.

**Closed** 2017-03-12 16:35 UTC
