### ISSUE TITLE
Can't install without nodejs

### ISSUE THREAD

**Issue by ao-il** [muammar/mkchromecast#70] opened 2017-06-05 15:01 UTC
Is nodejs required to install mkchromecast? This not stated in the requirements.

**Comment by muammar** [comment] 2017-06-05 15:42
> Is nodejs required to install mkchromecast? This not stated in the requirements.

What error are you getting?.

**Comment by ao-il** [comment] 2017-06-05 16:57
Can't post the output here as I am using a mobile phone, but it basically that dpkg won't install without nodejs because it a dependency. I have installed it with nodejs now but no sound with `mkchromecast --alsa-device hw1:1 --encoder-backend ffmpeg -c wav`.

**Comment by ao-il** [comment] 2017-06-05 18:57
Can't figure out what is going on, no sound, no error messages, even when I use invalid ffmpeg arguments.

**Comment by ao-il** [comment] 2017-06-05 21:37
This is what i have done, maybe it'll help to know what the problem is. First, I purged the old version of mkcc and then installed the latest .deb package from here (including mkchromecast-alsa). Initially, it did not install (because nodejs was missing) and i had use ´apt-get -f install´ to pull the dependencies along. Next, i loaded the alsa loopback device which i used in the argument list for the ffmpeg command, then pointed audacious to hw:1,0 of the loopback output. No sound, same thing before the purge and reinstallation. Is there something i have missed?
<pre><code>
mkchromecast --alsa-device hw:1,1 --encoder-backend ffmpeg -c wav 
The segment time has to be an integer number
Set to default of 2 seconds
The segment time has to be an integer number
Set to default of 2 seconds
Mkchromecast v0.3.7
Starting Local Streaming Server
[Done]
Selected backend: ffmpeg
Selected audio codec: wav
The wav codec does not require the bitrate argument.
Default sample rate used: 44100Hz
['ffmpeg', '-ac', '2', '-ar', '96k', '-sample_fmt', 'f32le', '-f', 'alsa', '-i', 'hw:1,1', '-f', 'wav', '-acodec', 'pcm_s24le', 'pipe:']
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
PID of main process: 4708
PID of streaming process: 4713
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Gcast 	CCAudio-NAD
 
We will cast to first device in the list above!
 
CCAudio-NAD
 
 
Information about  CCAudio-NAD
 
DeviceStatus(friendly_name=u'CCAudio-NAD', model_name=u'Chromecast Audio', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('4a5c41be-e018-8c13-5c13-0e713173cdae'), cast_type='audio')
 
Status of device  CCAudio-NAD
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=1.0, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of CCAudio-NAD is: 192.168.0.11
Your local IP is: 192.168.0.14
 
The media type string used is: audio/wav
 
Cast media controller status
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=1.0, volume_muted=False, app_id=u'CC1AD845', display_name=u'Default Media Receiver', namespaces=[u'urn:x-cast:com.google.cast.broadcast', u'urn:x-cast:com.google.cast.media'], session_id=u'6492e575-a072-43d2-8290-be0c27c9e74a', transport_id=u'6492e575-a072-43d2-8290-be0c27c9e74a', status_text=u'Ready To Cast')
 

Ctrl-C to kill the Application at any Time

192.168.0.11 - - [05/Jun/2017 17:21:10] "GET /stream HTTP/1.1" 200 -
^CKilled</code></pre>

**Comment by muammar** [comment] 2017-06-07 00:25
Probably the ffmpeg command is broken. I will take a look at that this weekend. Thanks.

**Comment by ao-il** [comment] 2017-06-26 16:01
Have you looked into this as promised?

**Comment by polyzen** [comment] 2017-06-26 18:50
Have you tried without specifying a codec?

**Comment by muammar** [comment] 2017-12-25 20:21
@ao-il Was this fixed in some way? I am sorry I was not able to look into it as promised... If the problem is not there I will proceed to close this report.

**Comment by ao-il** [comment] 2017-12-25 23:31
It is fine to close it.

**Closed** 2017-12-25 23:41 UTC
Labels: alsa, bug, Linux
