### ISSUE TITLE
Connects to chromecast audio through the system tray menu, but doesn't send audio 

### ISSUE THREAD

**Issue by Naomi1882** [muammar/mkchromecast#37] opened 2017-01-03 10:21 UTC
To start off, I know nothing about programming.

But right now this programme seems to be the only real alternative to soundcast, so I decided to give it a try by downloading the standalone macOS app and soundflower.

It does connect to the chromcast, it gives that lovely connected sound (with some delay).
It also sends through the sounds of my microphone (again with some delay), but no sound from any programme on my computer.
I have tried changing the sound output and input to both soundflower 2ch, and 64ch.

I am working with a macbook air, version 10.12, and a chromecast audio connected to a regular stereo amplifier.

What am I doing wrong?

**Comment by muammar** [comment] 2017-01-03 15:42
Hi, 

> To start off, I know nothing about programming.

Do not worry, that is fine. The idea behind this application is (hopefully) to be easy to use. 

> But right now this programme seems to be the only real alternative to soundcast, so I decided to give it a try by downloading the standalone macOS app and soundflower.

Can you let me know which version of soundflower have you installed? is it `2.0b2`?. The versions can be seen here: https://github.com/mattingalls/Soundflower/releases/. Have you installed the application using homebrew or just downloading and drag/drop?.

> It does connect to the chromcast, it gives that lovely connected sound (with some delay).
It also sends through the sounds of my microphone (again with some delay), but no sound from any programme on my computer.
I have tried changing the sound output and input to both soundflower 2ch, and 64ch.
>I am working with a macbook air, version 10.12, and a chromecast audio connected to a regular stereo amplifier.

>What am I doing wrong?

Good thing to try. This problem was found before, as you can [see here](https://github.com/muammar/mkchromecast/wiki/FAQ#it-seems-the-microphone-audio-is-being-cast-to-my-google-cast-device-in-macos). At that moment the problem was related to an old version of soundflower. If you have installed the latest one then we can try to look for another solution.

**Comment by Naomi1882** [comment] 2017-01-03 15:53
Hey,
Thanks for the reply.

The soundflower version I have installed is 2.0b2, and I have installed it by simply downloading and drag/drop.
This is the latest version, right?

**Comment by muammar** [comment] 2017-01-04 03:38
>Hey,
Thanks for the reply.

You are welcome.

>The soundflower version I have installed is 2.0b2, and I have installed it by simply downloading and drag/drop.
This is the latest version, right?

That is the latest version available. I have checked in three machines with MacOS: a MacBook pro late 2011 with Sierra installed, I cannot reproduce this problem. A MacBook pro retina 2015 with sierra installed, and a virtual box machine with Yosemite. 

I would suggest you uninstall soundflower, reboot, and reinstall it. Maybe it can solve the problem. The rest of the process is going fine since you hear the connecting sound.

**Comment by Naomi1882** [comment] 2017-01-04 15:07
It worked! 
I think at least, I also had to put the google cast volume up all the way to the max before I heard something.

But it works! So I am happy 

Just one last quick question, is there a way to only cast the sound of one app or browser tab?
If not, that is fine too, I am already very happy that I can cast my music to good speakers now :)

**Comment by muammar** [comment] 2017-01-04 15:15
>It worked!

Excellent :). So it confirms it was a problem with soundflower. 

>I think at least, I also had to put the google cast volume up all the way to the max before I heard something.

Yes, that's another detail I didn't suggest you to try. I remember when I was using soundcast, sometimes the problem with low volumes was related to the impossibility of control it. 


>But it works! So I am happy

Glad it worked. 

>Just one last quick question, is there a way to only cast the sound of one app or browser tab?
If not, that is fine too, I am already very happy that I can cast my music to good speakers now :)

Soundflower redirects all audio in your mac, therefore this is not possible in macOS :(. In Linux using pulseaudio one can achieve what you want. I know there is a way of installing other sound servers in macOS like pulseaudio, but then using the application will require lots of work and tweaking. 

Please, feel free to close this bug report and to open another one if you need anything else. 

Regards.

**Closed** 2017-01-04 15:16 UTC
Labels: macOS
