### ISSUE TITLE
install: cannot stat 'LICENSE': No such file or directory

### ISSUE THREAD

**Issue by riguco** [muammar/mkchromecast#65] opened 2017-05-02 01:05 UTC
Hi,

i'm trying to install mkchromecast-git from yaourt and get this error:

install: cannot stat 'LICENSE': No such file or directory

someone can help me ?

**Comment by muammar** [comment] 2017-05-02 14:45
The problem is because I renamed from `LICENSE` to `LICENSE.rst`. @terencode told me he will try to update the yaourt package, but if you have access to `PKGBUILD` file, just search for `LICENSE` and rename it to `LICENSE.rst`:

```
diff --git a/PKGBUILD b/PKGBUILD
index 39d7302..40af89c 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -15,7 +15,7 @@ optdepends=('ffmpeg'
             'python-pyqt5: system tray menu support'
             'youtube-dl: youtube URLs casting support')
 options=('!emptydirs')
-source=("git+https://github.com/muammar/${_gitname}.git#branch=devel" 
+source=("git+https://github.com/muammar/${_gitname}.git#branch=devel"
 "mkchromecast.sh" "mkchromecast.desktop" "mkchromecast.png")
 md5sums=('SKIP' 'SKIP' 'SKIP' 'SKIP')
 
@@ -37,7 +37,7 @@ package() {
   install -D -m644 images/* "${pkgdir}/usr/share/mkchromecast/images/"
 
   install -D -m755 ../mkchromecast.sh "${pkgdir}/usr/bin/mkchromecast"
-  install -D -m644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  install -D -m644 LICENSE.rst "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE.rst"
   install -D -m644 ../mkchromecast.png "${pkgdir}/usr/share/icons/hicolor/128x128/apps/mkchromecast.png"
   install -D -m644 ../mkchromecast.desktop "${pkgdir}/usr/share/applications/mkchromecast.desktop"
 }
```

**Comment by terencode** [comment] 2017-05-02 15:26
@riguco I'll update the package this evening.

**Comment by muammar** [comment] 2017-05-05 20:37
@riguco by now @terencode has updated the yaourt package. I will proceed to close this report. Please, feel free to reopen if you still have issues.

**Comment by terencode** [comment] 2017-05-05 20:37
@riguco package updated, please try again and in the future report package issue on the AUR, not in github.

**Closed by muammar** 2017-05-05 20:37 UTC
Labels: Linux, packaging

**Comment by riguco** [comment] 2017-05-07 14:54
Ok, thx! I successfully installed.
